#!/usr/bin/env python3
r"""Generate the Unicode range tables the ByteLevel pre-tokenizer's regex needs.

`tokenizers` splits with the Rust `regex` crate, on the original UTF-8 text:

    's|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+

`\p{L}` is the general category L (Lu/Ll/Lt/Lm/Lo), `\p{N}` is N (Nd/Nl/No), and `\s`
is the White_Space property. Zig has none of that, so the three classes are baked into
src/unicode_tables.zig as sorted, disjoint (start, end) ranges that the Zig side
binary-searches.

Usage:

    python3 ggml/tools/gen_unicode_tables.py ggml/src/unicode_tables.zig

Stdlib only. The tables follow whatever Unicode version the interpreter ships
(unicodedata.unidata_version) -- the script prints it and writes it into the generated
header. That is the one thing to watch: `tokenizers` builds its own tables from the
`regex` crate, so an interpreter older than the crate disagrees with it on codepoints
assigned in between, and the disagreement shows up as a wrong split (a codepoint that
should have merged into a neighbouring word) rather than as an error. Python 3.14 ships
Unicode 16.0.0, which is what `regex` 1.11+ (and therefore current `tokenizers`) uses;
check the printed version if you regenerate with something older.
"""

import sys
import unicodedata

# The White_Space property, from Unicode's PropList.txt. It is tiny and fixed, so it is
# written out rather than derived: unicodedata exposes general categories, not the
# binary properties, and Python's str.isspace() is NOT the same set (it also accepts
# U+001C..U+001F, which White_Space excludes).
WHITE_SPACE = [
    0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680,
    0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009,
    0x200A, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
]

LAST = 0x10FFFF


def ranges(pred):
    """Sorted, disjoint inclusive (start, end) ranges of the codepoints pred accepts."""
    out = []
    start = None
    for cp in range(LAST + 1):
        ok = not (0xD800 <= cp <= 0xDFFF) and pred(cp)  # surrogates are not characters
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, LAST))
    return out


def emit(f, name, rs):
    f.write("pub const {} = [_][2]u32{{\n".format(name))
    for i in range(0, len(rs), 6):
        row = ", ".join(".{{ 0x{:04X}, 0x{:04X} }}".format(*r) for r in rs[i:i + 6])
        f.write("    {},\n".format(row))
    f.write("};\n\n")


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    letter = ranges(lambda cp: unicodedata.category(chr(cp))[0] == "L")
    number = ranges(lambda cp: unicodedata.category(chr(cp))[0] == "N")
    ws = set(WHITE_SPACE)
    white = ranges(lambda cp: cp in ws)

    out = []
    out.append("//! Unicode range tables for the ByteLevel pre-tokenizer's regex.\n")
    out.append("//!\n")
    out.append("//! GENERATED by tools/gen_unicode_tables.py -- do not edit by hand.\n")
    out.append("//! Unicode {}, from Python {} unicodedata.\n".format(
        unicodedata.unidata_version, ".".join(map(str, sys.version_info[:3]))))
    out.append("//! Regenerate with: python3 ggml/tools/gen_unicode_tables.py ggml/src/unicode_tables.zig\n")
    out.append("//!\n")
    out.append("//! `letter` is \\p{{L}} ({} ranges), `number` is \\p{{N}} ({}), `white_space` is the\n".format(
        len(letter), len(number)))
    out.append("//! White_Space property ({}). Ranges are sorted, disjoint and inclusive.\n".format(len(white)))
    out.append("\n")
    out.append("/// Unicode version the tables below were generated from.\n")
    out.append('pub const version = "{}";\n\n'.format(unicodedata.unidata_version))
    out.append("/// True when `cp` lies in `rs`, a sorted, disjoint, inclusive range list.\n")
    out.append("pub fn inRanges(rs: []const [2]u32, cp: u32) bool {\n")
    out.append("    var lo: usize = 0;\n")
    out.append("    var hi: usize = rs.len;\n")
    out.append("    while (lo < hi) {\n")
    out.append("        const mid = lo + (hi - lo) / 2;\n")
    out.append("        if (cp < rs[mid][0]) {\n")
    out.append("            hi = mid;\n")
    out.append("        } else if (cp > rs[mid][1]) {\n")
    out.append("            lo = mid + 1;\n")
    out.append("        } else {\n")
    out.append("            return true;\n")
    out.append("        }\n")
    out.append("    }\n")
    out.append("    return false;\n")
    out.append("}\n\n")

    import io
    tmp = io.StringIO()
    emit(tmp, "letter", letter)
    emit(tmp, "number", number)
    emit(tmp, "white_space", white)
    out.append(tmp.getvalue())

    with open(argv[1], "w") as f:
        f.write("".join(out))
    print("wrote {}: unicode {}, {} letter / {} number / {} white_space ranges".format(
        argv[1], unicodedata.unidata_version, len(letter), len(number), len(white)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
