//! SmolLM2 tokenizer: text -> ids, and back, matching HuggingFace `tokenizers` for
//! .weights/model_dir/processor/tokenizer.json (byte-level BPE: 49152 vocab tokens plus
//! 145 added specials).
//!
//! Three stages, in this order, and the order is load bearing:
//!
//!   1. Added tokens first. All 145 `added_tokens` are `special`, `normalized: false`,
//!      with no lstrip/rstrip, so this is a plain left-to-right longest match: emit the id,
//!      skip the content, repeat. Everything between two added tokens goes through the
//!      rest. That is what makes `<|im_start|>` one id instead of six.
//!   2. The ByteLevel split, GPT-2's regex:
//!        's|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+
//!      Leftmost-first: at each position the alternatives are tried in that order and the
//!      first that matches wins. It runs on the ORIGINAL UTF-8 TEXT, never on the
//!      byte-encoded form -- splitting the encoded form gives different pieces for every
//!      byte >= 0x80.
//!   3. Byte encode + BPE. Each byte of a piece maps to one printable codepoint (GPT-2's
//!      bytes_to_unicode: 33..126, 161..172 and 174..255 map to themselves, the other 68
//!      bytes map to 256+i in increasing byte order, so 0x20 -> U+0120 and 0x0A -> U+010A).
//!      Those characters are the symbols. Repeatedly merge the adjacent symbol pair with
//!      the lowest `merges` rank, then look the surviving symbols up in `vocab`.
//!
//! What the reference corpus (.weights/oracle/tok_ref.bin) pins down, checked rather than
//! assumed:
//!
//!   * `\s+(?!\S)` backtracks. It takes the whole whitespace run when that run ends at
//!     end-of-text or is followed by a non-space, and otherwise gives back exactly ONE
//!     character. Hence "a\r\nb" -> "a" / "\r" / "\n" / "b": the "\r\n" run sees 'b', gives
//!     one back, and the leftover "\n" falls through to the final `\s+`.
//!   * ` ?` is a single optional U+0020, nothing more: "a  b" is "a" / " " / " b", and
//!     "a   b" is "a" / "  " / " b".
//!   * \p{L}, \p{N} and \s are Unicode-wide, from unicode_tables.zig (generated by
//!     tools/gen_unicode_tables.py). \s is the White_Space property, which is NOT the same
//!     set as Python's str.isspace() (U+001C..U+001F are not White_Space).
//!   * 21 of the 256 single-byte symbols are absent from this vocab: 0x04, 0x06, 0x13,
//!     0x14, 0x16, 0x1d, 0xc0, 0xc1 and 0xf1, 0xf2, 0xf5..0xff. `unk_token` is null and
//!     `byte_fallback` is false, so HuggingFace drops a symbol it cannot find -- "a\x04b"
//!     really is [81, 82] in the reference, the 0x04 just vanishes. We drop the same way,
//!     and count it. The drop happens BEFORE the merge loop, never after: the surviving
//!     symbols on either side of a dropped one become adjacent and can merge, so `"` +
//!     0x1d + `+` (one piece) encodes to the single token `"+` (id 30541), not to `"`,`+`.
//!     No row of the reference corpus exercises that -- every drop there sits at a piece
//!     boundary or next to a pair with no merge rule -- which is why the order is pinned
//!     down here rather than left to the corpus.
//!
//! The BPE loop never touches strings: symbols are interned to dense u32 ids at load, each
//! byte has a precomputed starting symbol id, and the merge table is a hashmap from a
//! packed (left, right) symbol pair to its rank plus a rank-indexed table of merged
//! symbols.
//!
//! Usage: tokenizer <tok_ref.bin> <tokenizer.json>

const std = @import("std");
const uni = @import("unicode_tables.zig");

/// Largest codepoint the byte-level encoding produces (0xff -> 323), so the inverse table
/// used by decode is this long.
const enc_cp_max = 324;

var io_g: std.Io = undefined;
var io_set = false;
var io_fallback: std.Io.Threaded = undefined;

/// Io instance for file reads. main() hands us the real one; a caller that only wants
/// `Tokenizer.load` gets a lazily built fallback, because the load signature carries no io.
fn io(alloc: std.mem.Allocator) std.Io {
    if (!io_set) {
        io_fallback = std.Io.Threaded.init(alloc, .{});
        io_g = io_fallback.io();
        io_set = true;
    }
    return io_g;
}

fn readFile(alloc: std.mem.Allocator, path: []const u8) ![]u8 {
    return std.Io.Dir.cwd().readFileAlloc(io(alloc), path, alloc, std.Io.Limit.limited(1 << 30));
}

/// An added (special) token: a literal byte string, matched before anything else.
const Added = struct { id: u32, content: []const u8 };

pub const Tokenizer = struct {
    /// Owns every string below, and the tables keyed by them.
    arena: std.heap.ArenaAllocator,

    /// Symbol interning: a BPE symbol is a string of byte-encoded characters; symbols are
    /// dense u32 ids so the merge loop never looks at a string.
    intern: std.StringHashMapUnmanaged(u32),
    syms: std.ArrayList([]const u8),
    /// vocab id of each symbol, -1 when the symbol is not a vocab key (dropped, see above).
    sym_vocab: std.ArrayList(i32),

    /// (left << 32 | right) -> rank in `merges`; merge_result[rank] is the merged symbol.
    ranks: std.AutoHashMapUnmanaged(u64, u32),
    merge_result: std.ArrayList(u32),

    /// byte -> symbol id of the character that byte encodes to.
    byte_sym: [256]u32,
    /// codepoint -> byte, the inverse, for decode.
    cp_byte: [enc_cp_max]i16,

    /// added tokens, longest content first so the first match at a position is the longest.
    added: []const Added,
    /// whether any added token starts with this byte (skips the scan for most positions).
    could_start: [256]bool = @splat(false),
    /// vocab id -> its vocab string; null when the id is not a base-vocab token.
    tok_str: []const ?[]const u8,
    /// vocab id -> added-token content; null when the id is not an added token.
    added_str: []const ?[]const u8,

    n_vocab: usize,
    n_merges: usize,
    n_added: usize,

    pub fn load(alloc: std.mem.Allocator, tokenizer_json_path: []const u8) !Tokenizer {
        var self = Tokenizer{
            .arena = std.heap.ArenaAllocator.init(alloc),
            .intern = .empty,
            .syms = .empty,
            .sym_vocab = .empty,
            .ranks = .empty,
            .merge_result = .empty,
            .byte_sym = undefined,
            .cp_byte = undefined,
            .added = &.{},
            .tok_str = &.{},
            .added_str = &.{},
            .n_vocab = 0,
            .n_merges = 0,
            .n_added = 0,
        };
        errdefer self.deinit();
        const a = self.arena.allocator();

        const raw = try readFile(alloc, tokenizer_json_path);
        defer alloc.free(raw);
        // std.json keeps strings as slices into `raw` where it can, so `raw` outlives the
        // whole load -- everything we keep is interned (copied) into the arena first.
        var parsed = try std.json.parseFromSlice(std.json.Value, alloc, raw, .{});
        defer parsed.deinit();

        const root = switch (parsed.value) {
            .object => |o| o,
            else => return error.BadTokenizerJson,
        };
        const model = switch (try field(root, "model")) {
            .object => |o| o,
            else => return error.BadTokenizerJson,
        };
        const vocab = switch (try field(model, "vocab")) {
            .object => |o| o,
            else => return error.BadTokenizerJson,
        };
        const merges = switch (try field(model, "merges")) {
            .array => |ar| ar,
            else => return error.BadTokenizerJson,
        };
        const added_json = switch (try field(root, "added_tokens")) {
            .array => |ar| ar,
            else => return error.BadTokenizerJson,
        };
        const model_type = switch (try field(model, "type")) {
            .string => |s| s,
            else => return error.BadTokenizerJson,
        };
        if (!std.mem.eql(u8, model_type, "BPE")) return error.NotByteLevelBpe;

        // The id space is the union of the vocab and the added tokens; the added ids sit
        // past the end of the vocab (49152..49279 here).
        var max_id: usize = 0;
        {
            var it = vocab.iterator();
            while (it.next()) |e| {
                const id: usize = @intCast(try intField(e.value_ptr.*));
                if (id > max_id) max_id = id;
            }
            for (added_json.items) |tv| {
                const o = switch (tv) {
                    .object => |o| o,
                    else => return error.BadTokenizerJson,
                };
                const id: usize = @intCast(try intField(try field(o, "id")));
                if (id > max_id) max_id = id;
            }
        }
        const n_ids = max_id + 1;
        const tok_str = try a.alloc(?[]const u8, n_ids);
        @memset(tok_str, null);
        const added_str = try a.alloc(?[]const u8, n_ids);
        @memset(added_str, null);

        // bytes_to_unicode, both directions.
        for (0..256) |b| {
            const cp = byteToCodepoint(@intCast(b));
            std.debug.assert(cp < enc_cp_max);
            var buf: [4]u8 = undefined;
            const n = try std.unicode.utf8Encode(@intCast(cp), &buf);
            self.byte_sym[b] = try self.internSymbol(a, buf[0..n]);
        }
        @memset(&self.cp_byte, -1);
        for (0..256) |b| self.cp_byte[byteToCodepoint(@intCast(b))] = @intCast(b);

        // vocab: token string -> id, and back.
        {
            var it = vocab.iterator();
            while (it.next()) |e| {
                const id: usize = @intCast(try intField(e.value_ptr.*));
                const sym = try self.internSymbol(a, e.key_ptr.*);
                self.sym_vocab.items[sym] = @intCast(id);
                tok_str[id] = self.syms.items[sym];
                self.n_vocab += 1;
            }
        }

        // merges: the pair and its result are interned, the result usually being a vocab
        // key that was interned a moment ago.
        try self.ranks.ensureTotalCapacity(a, @intCast(merges.items.len));
        try self.merge_result.ensureTotalCapacity(a, merges.items.len);
        for (merges.items, 0..) |mv, rank| {
            var left: []const u8 = undefined;
            var right: []const u8 = undefined;
            switch (mv) {
                // Newer tokenizers files store merges as ["l", "r"] pairs; older ones as
                // the single string "l r". Both appear in the wild, so accept both.
                .array => |pair| {
                    if (pair.items.len != 2) return error.BadTokenizerJson;
                    left = switch (pair.items[0]) {
                        .string => |s| s,
                        else => return error.BadTokenizerJson,
                    };
                    right = switch (pair.items[1]) {
                        .string => |s| s,
                        else => return error.BadTokenizerJson,
                    };
                },
                .string => |s| {
                    const sp = std.mem.indexOfScalar(u8, s, ' ') orelse return error.BadTokenizerJson;
                    left = s[0..sp];
                    right = s[sp + 1 ..];
                },
                else => return error.BadTokenizerJson,
            }
            const l = try self.internSymbol(a, left);
            const r = try self.internSymbol(a, right);
            const joined = try std.mem.concat(a, u8, &.{ left, right });
            const m = try self.internSymbol(a, joined);
            self.ranks.putAssumeCapacity(pairKey(l, r), @intCast(rank));
            self.merge_result.appendAssumeCapacity(m);
            self.n_merges += 1;
        }

        // added tokens: longest first, so a match at a position is already the longest.
        {
            var list: std.ArrayList(Added) = .empty;
            for (added_json.items) |tv| {
                const o = switch (tv) {
                    .object => |o| o,
                    else => return error.BadTokenizerJson,
                };
                const id: u32 = @intCast(try intField(try field(o, "id")));
                const content = switch (try field(o, "content")) {
                    .string => |s| s,
                    else => return error.BadTokenizerJson,
                };
                const owned = try a.dupe(u8, content);
                try list.append(a, .{ .id = id, .content = owned });
                added_str[id] = owned;
                self.n_added += 1;
            }
            std.mem.sort(Added, list.items, {}, addedLongestFirst);
            self.added = try list.toOwnedSlice(a);
            for (self.added) |ad| {
                if (ad.content.len > 0) self.could_start[ad.content[0]] = true;
            }
        }

        self.tok_str = tok_str;
        self.added_str = added_str;
        return self;
    }

    pub fn deinit(self: *Tokenizer) void {
        self.arena.deinit();
        self.* = undefined;
    }

    /// text -> ids. Ids come back allocated with `alloc`; the caller frees them.
    pub fn encode(self: *const Tokenizer, alloc: std.mem.Allocator, text: []const u8) ![]u32 {
        var drops: usize = 0;
        return self.encodeCounted(alloc, text, &drops);
    }

    /// `encode`, plus how many symbols were dropped for having no vocab id. 134 of the
    /// corpus rows' symbols go this way in the reference too (see the header).
    pub fn encodeCounted(self: *const Tokenizer, alloc: std.mem.Allocator, text: []const u8, drops: *usize) ![]u32 {
        var out: std.ArrayList(u32) = .empty;
        errdefer out.deinit(alloc);
        const scratch = try alloc.alloc(u32, text.len);
        defer alloc.free(scratch);
        var ctx = EncodeCtx{ .alloc = alloc, .tk = self, .out = &out, .scratch = scratch, .drops = drops };
        try self.walk(text, &ctx);
        return out.toOwnedSlice(alloc);
    }

    /// ids -> bytes. Byte-level tokens are mapped back to the bytes they came from and
    /// added tokens contribute their literal content; the concatenation is then made valid
    /// UTF-8 with U+FFFD, because a single token can hold half a multi-byte character.
    pub fn decode(self: *const Tokenizer, alloc: std.mem.Allocator, ids: []const u32) ![]u8 {
        var raw: std.ArrayList(u8) = .empty;
        defer raw.deinit(alloc);
        for (ids) |id| {
            if (@as(usize, id) >= self.tok_str.len) return error.UnknownTokenId;
            if (self.tok_str[id]) |s| {
                var k: usize = 0;
                while (k < s.len) {
                    const d = decode1(s[k..]);
                    if (d.cp >= enc_cp_max or self.cp_byte[d.cp] < 0) return error.BadVocabToken;
                    try raw.append(alloc, @intCast(self.cp_byte[d.cp]));
                    k += d.len;
                }
            } else if (self.added_str[id]) |s| {
                try raw.appendSlice(alloc, s);
            } else {
                return error.UnknownTokenId;
            }
        }
        return lossyUtf8(alloc, raw.items);
    }

    // ---- internals ------------------------------------------------------------------

    /// Intern `s`, copying it into the arena the first time. The returned id indexes
    /// `syms`/`sym_vocab`.
    fn internSymbol(self: *Tokenizer, a: std.mem.Allocator, s: []const u8) !u32 {
        const gop = try self.intern.getOrPut(a, s);
        if (gop.found_existing) return gop.value_ptr.*;
        const owned = try a.dupe(u8, s);
        gop.key_ptr.* = owned;
        const id: u32 = @intCast(self.syms.items.len);
        try self.syms.append(a, owned);
        try self.sym_vocab.append(a, -1);
        gop.value_ptr.* = id;
        return id;
    }

    /// Split `text` into added tokens and regex pieces, handing each to `ctx`, which must
    /// provide `onSpecial(self, id: u32) !void` and `onPiece(self, bytes: []const u8) !void`.
    fn walk(self: *const Tokenizer, text: []const u8, ctx: anytype) !void {
        var i: usize = 0;
        while (i < text.len) {
            if (self.matchAdded(text, i)) |hit| {
                try ctx.onSpecial(hit.id);
                i += hit.content.len;
                continue;
            }
            const end = self.nextAdded(text, i);
            var p = i;
            while (p < end) {
                const n = pieceLen(text[p..end]);
                try ctx.onPiece(text[p .. p + n]);
                p += n;
            }
            i = end;
        }
    }

    /// The added token starting at `text[i]`, if any. `added` is longest-first, so the
    /// first hit is the longest match.
    fn matchAdded(self: *const Tokenizer, text: []const u8, i: usize) ?Added {
        if (!self.could_start[text[i]]) return null;
        for (self.added) |ad| {
            if (std.mem.startsWith(u8, text[i..], ad.content)) return ad;
        }
        return null;
    }

    /// Offset of the next added token at or after `from`, or text.len.
    fn nextAdded(self: *const Tokenizer, text: []const u8, from: usize) usize {
        var i = from;
        while (i < text.len) : (i += 1) {
            if (self.matchAdded(text, i) != null) return i;
        }
        return text.len;
    }

    /// Byte-encode one piece into `scratch` (which must hold at least `piece.len` u32s),
    /// drop the symbols that have no vocab id, merge what is left, and return the
    /// survivors. `dropped` receives how many were removed.
    ///
    /// The drop happens BEFORE the merge, and that ordering is observable. `"` + the 0x1d
    /// byte (U+011D) + `+` is one piece; U+011D is not a vocab key, and once it is gone the
    /// `"` and `+` are adjacent, so they merge into the single token `"+` (id 30541).
    /// Dropping after the merge leaves two ids there instead. HuggingFace's `merge_word`
    /// builds its word out of the characters that are in the vocab, i.e. exactly this
    /// order; `.weights/oracle/tok_ref.bin` on its own cannot tell the two apart, because
    /// none of its rows has a mergeable pair on either side of a dropped symbol.
    fn encodePiece(self: *const Tokenizer, piece: []const u8, scratch: []u32, dropped: *usize) []u32 {
        std.debug.assert(scratch.len >= piece.len);
        var n: usize = 0;
        for (piece) |b| {
            const sym = self.byte_sym[b];
            if (self.sym_vocab.items[sym] < 0) {
                dropped.* += 1;
                continue;
            }
            scratch[n] = sym;
            n += 1;
        }
        const m = self.mergeSymbols(scratch[0..n]);
        return scratch[0..m];
    }

    /// Merge `syms` in place and return how many symbols survive. HuggingFace picks the
    /// pair with the lowest rank, merges every non-overlapping occurrence of it left to
    /// right, and repeats until no adjacent pair has a rank.
    fn mergeSymbols(self: *const Tokenizer, syms: []u32) usize {
        var n = syms.len;
        while (n > 1) {
            var best: u32 = std.math.maxInt(u32);
            var at: usize = 0;
            var found = false;
            var x: usize = 0;
            while (x + 1 < n) : (x += 1) {
                if (self.ranks.get(pairKey(syms[x], syms[x + 1]))) |r| {
                    if (!found or r < best) {
                        best = r;
                        at = x;
                        found = true;
                    }
                }
            }
            if (!found) break;
            const left = syms[at];
            const right = syms[at + 1];
            const merged = self.merge_result.items[best];
            var w: usize = 0;
            x = 0;
            while (x < n) {
                if (x + 1 < n and syms[x] == left and syms[x + 1] == right) {
                    syms[w] = merged;
                    w += 1;
                    x += 2;
                } else {
                    syms[w] = syms[x];
                    w += 1;
                    x += 1;
                }
            }
            n = w;
        }
        return n;
    }
};

fn field(obj: std.json.ObjectMap, name: []const u8) !std.json.Value {
    return obj.get(name) orelse error.BadTokenizerJson;
}

fn intField(v: std.json.Value) !i64 {
    return switch (v) {
        .integer => |i| i,
        else => error.BadTokenizerJson,
    };
}

fn addedLongestFirst(_: void, x: Added, y: Added) bool {
    return x.content.len > y.content.len;
}

fn pairKey(left: u32, right: u32) u64 {
    return (@as(u64, left) << 32) | @as(u64, right);
}

/// GPT-2's bytes_to_unicode: 33..126, 161..172 and 174..255 are themselves; the other 68
/// bytes get 256+i in increasing byte order.
fn byteToCodepoint(b: u32) u32 {
    if (isUnmappedPassthrough(b)) return b;
    var n: u32 = 0;
    var x: u32 = 0;
    while (x < b) : (x += 1) {
        if (!isUnmappedPassthrough(x)) n += 1;
    }
    return 256 + n;
}

fn isUnmappedPassthrough(b: u32) bool {
    return (b >= 33 and b <= 126) or (b >= 161 and b <= 172) or (b >= 174 and b <= 255);
}

const Cp = struct { cp: u32, len: usize };

/// Decode one UTF-8 sequence at the front of `s`. Anything malformed comes back as a
/// single one-byte character, which lands in the "other" class -- the regex crate refuses
/// invalid UTF-8 outright, so there is no reference behaviour to match there.
fn decode1(s: []const u8) Cp {
    const b0 = s[0];
    if (b0 < 0x80) return .{ .cp = b0, .len = 1 };
    const n: usize = switch (b0) {
        0xC2...0xDF => 2,
        0xE0...0xEF => 3,
        0xF0...0xF4 => 4,
        else => return .{ .cp = 0xFFFD, .len = 1 },
    };
    if (s.len < n) return .{ .cp = 0xFFFD, .len = 1 };
    var cp: u32 = switch (n) {
        2 => b0 & 0x1F,
        3 => b0 & 0x0F,
        else => b0 & 0x07,
    };
    for (s[1..n]) |b| {
        if (b & 0xC0 != 0x80) return .{ .cp = 0xFFFD, .len = 1 };
        cp = (cp << 6) | (b & 0x3F);
    }
    return .{ .cp = cp, .len = n };
}

fn isLetter(cp: u32) bool {
    return uni.inRanges(&uni.letter, cp);
}
fn isNumber(cp: u32) bool {
    return uni.inRanges(&uni.number, cp);
}
fn isSpace(cp: u32) bool {
    return uni.inRanges(&uni.white_space, cp);
}

const Class = enum { letter, number, other };

/// End offset of the maximal run of `kind` starting at `from`.
fn classRun(s: []const u8, from: usize, kind: Class) usize {
    var i = from;
    while (i < s.len) {
        const d = decode1(s[i..]);
        const ok = switch (kind) {
            .letter => isLetter(d.cp),
            .number => isNumber(d.cp),
            // `[^\s\p{L}\p{N}]`: the complement, so the three classes together cover every
            // codepoint and the split is always total.
            .other => !isSpace(d.cp) and !isLetter(d.cp) and !isNumber(d.cp),
        };
        if (!ok) break;
        i += d.len;
    }
    return i;
}

fn spaceRun(s: []const u8, from: usize) usize {
    var i = from;
    while (i < s.len) {
        const d = decode1(s[i..]);
        if (!isSpace(d.cp)) break;
        i += d.len;
    }
    return i;
}

/// Byte length of the piece the ByteLevel regex matches at the front of `s` (non-empty).
///
///     's|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+
///
/// Leftmost-first: the alternatives below are tried in that order and the first match wins.
fn pieceLen(s: []const u8) usize {
    if (s[0] == '\'') {
        const suffixes = [_][]const u8{ "s", "t", "re", "ve", "m", "ll", "d" };
        for (suffixes) |sf| {
            if (std.mem.startsWith(u8, s[1..], sf)) return 1 + sf.len;
        }
    }
    // ` ?` lets the piece start with one space, but only the letters/numbers/others
    // alternatives take it; if what follows the space is not of that class, the
    // alternative fails and the space is dealt with further down.
    const off: usize = if (s[0] == ' ') 1 else 0;
    inline for (.{ Class.letter, Class.number, Class.other }) |kind| {
        const end = classRun(s, off, kind);
        if (end > off) return end;
    }
    // \s+(?!\S): greedy, then the lookahead; on failure it gives back one CHARACTER (not
    // one byte -- a whitespace run can be a single 2-byte character, e.g. NBSP), and when
    // the run holds a single character there is nothing to give back, so the alternative
    // fails and the plain `\s+` below takes exactly that character.
    const run = spaceRun(s, 0);
    if (run == s.len) return run;
    var last_start: usize = 0;
    var chars: usize = 0;
    var i: usize = 0;
    while (i < run) {
        const d = decode1(s[i..]);
        last_start = i;
        chars += 1;
        i += d.len;
    }
    if (chars >= 2) return last_start;
    return run;
}

/// A row of the reference corpus: the ground-truth ids for `text`, plus the
/// pre-tokenizer split with the ids each piece yields on its own.
const Piece = struct { text: []const u8, ids: []const u32 };
const Row = struct { label: []const u8, text: []const u8, ids: []const u32, pieces: []const Piece };

const Cursor = struct {
    b: []const u8,
    i: usize = 0,

    fn u32le(self: *Cursor) !u32 {
        if (self.i + 4 > self.b.len) return error.TruncatedRef;
        const v = std.mem.readInt(u32, self.b[self.i..][0..4], .little);
        self.i += 4;
        return v;
    }

    /// u32 length followed by that many raw bytes.
    fn blob(self: *Cursor) ![]const u8 {
        const n = try self.u32le();
        if (self.i + n > self.b.len) return error.TruncatedRef;
        const s = self.b[self.i .. self.i + n];
        self.i += n;
        return s;
    }

    /// u32 count followed by that many little-endian i32s (which are ids, all >= 0).
    fn ids(self: *Cursor, alloc: std.mem.Allocator) ![]const u32 {
        const n = try self.u32le();
        if (self.i + @as(usize, n) * 4 > self.b.len) return error.TruncatedRef;
        const out = try alloc.alloc(u32, n);
        for (out, 0..) |*o, k| o.* = std.mem.readInt(u32, self.b[self.i + k * 4 ..][0..4], .little);
        self.i += @as(usize, n) * 4;
        return out;
    }
};

fn readRef(alloc: std.mem.Allocator, bytes: []const u8) ![]Row {
    if (bytes.len < 8 or !std.mem.eql(u8, bytes[0..4], "TOKR")) return error.BadRefMagic;
    var cur = Cursor{ .b = bytes, .i = 4 };
    const n_rows = try cur.u32le();
    const rows = try alloc.alloc(Row, n_rows);
    for (rows) |*row| {
        const label = try cur.blob();
        const text = try cur.blob();
        const row_ids = try cur.ids(alloc);
        const n_pieces = try cur.u32le();
        const pieces = try alloc.alloc(Piece, n_pieces);
        for (pieces) |*pc| {
            pc.text = try cur.blob();
            pc.ids = try cur.ids(alloc);
        }
        row.* = .{ .label = label, .text = text, .ids = row_ids, .pieces = pieces };
    }
    if (cur.i != bytes.len) return error.RefTrailingBytes;
    return rows;
}

const EncodeCtx = struct {
    alloc: std.mem.Allocator,
    tk: *const Tokenizer,
    out: *std.ArrayList(u32),
    scratch: []u32,
    drops: *usize,

    fn onSpecial(self: *EncodeCtx, id: u32) !void {
        try self.out.append(self.alloc, id);
    }

    fn onPiece(self: *EncodeCtx, bytes: []const u8) !void {
        const syms = self.tk.encodePiece(bytes, self.scratch, self.drops);
        for (syms) |sym| {
            const id = self.tk.sym_vocab.items[sym];
            if (id < 0) {
                // Not reachable through encodePiece, which drops those already; counted
                // rather than asserted so a corrupt merge table lands in the report.
                self.drops.* += 1;
                continue;
            }
            try self.out.append(self.alloc, @intCast(id));
        }
    }
};

/// Prints a split the way the reference file stores it: pieces byte-encoded (so a space
/// prints as U+0120), each followed by the ids it yields.
const DumpCtx = struct {
    alloc: std.mem.Allocator,
    tk: *const Tokenizer,
    scratch: []u32,
    printed: usize = 0,

    fn onSpecial(self: *DumpCtx, id: u32) !void {
        _ = self;
        std.debug.print("      <added {d}>\n", .{id});
    }

    fn onPiece(self: *DumpCtx, bytes: []const u8) !void {
        if (self.printed >= 24) return;
        self.printed += 1;
        const shown = try encodePreview(self.alloc, bytes, 24);
        defer self.alloc.free(shown);
        std.debug.print("      '{s}' = ", .{shown});
        var dropped: usize = 0;
        const syms = self.tk.encodePiece(bytes, self.scratch, &dropped);
        std.debug.print("(", .{});
        for (syms, 0..) |sym, k| {
            if (k > 0) std.debug.print(",", .{});
            std.debug.print("{d}", .{self.tk.sym_vocab.items[sym]});
        }
        std.debug.print(")", .{});
        if (dropped > 0) std.debug.print(" [{d} symbol(s) dropped before the merges]", .{dropped});
        std.debug.print("\n", .{});
    }
};

/// The byte-encoded form of `bytes`, for printing next to the reference's pieces, capped
/// at `cap` bytes with a trailing "...".
fn encodePreview(alloc: std.mem.Allocator, bytes: []const u8, cap: usize) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(alloc);
    for (bytes[0..@min(bytes.len, cap)]) |b| {
        var buf: [4]u8 = undefined;
        const n = try std.unicode.utf8Encode(@intCast(byteToCodepoint(b)), &buf);
        try out.appendSlice(alloc, buf[0..n]);
    }
    if (bytes.len > cap) try out.appendSlice(alloc, "...");
    return out.toOwnedSlice(alloc);
}

/// `text` with control bytes escaped and the whole thing capped, for readable reports.
fn textPreview(alloc: std.mem.Allocator, text: []const u8, cap: usize) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(alloc);
    for (text[0..@min(text.len, cap)]) |b| {
        if (b == '\n') {
            try out.appendSlice(alloc, "\\n");
        } else if (b == '\r') {
            try out.appendSlice(alloc, "\\r");
        } else if (b == '\t') {
            try out.appendSlice(alloc, "\\t");
        } else if (b < 0x20 or b == 0x7F) {
            var buf: [8]u8 = undefined;
            try out.appendSlice(alloc, try std.fmt.bufPrint(&buf, "\\x{x:0>2}", .{b}));
        } else {
            try out.append(alloc, b);
        }
    }
    if (text.len > cap) try out.appendSlice(alloc, "...");
    return out.toOwnedSlice(alloc);
}

fn printIds(prefix: []const u8, ids: []const u32) void {
    std.debug.print("{s}[", .{prefix});
    for (ids[0..@min(ids.len, 24)], 0..) |id, k| {
        if (k > 0) std.debug.print(", ", .{});
        std.debug.print("{d}", .{id});
    }
    if (ids.len > 24) std.debug.print(", ...", .{});
    std.debug.print("]\n", .{});
}

/// Replace invalid UTF-8 with U+FFFD, one per maximal subpart, which is what Rust's
/// from_utf8_lossy does -- and id sequences here really can split a character in half.
fn lossyUtf8(alloc: std.mem.Allocator, bytes: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(alloc);
    var i: usize = 0;
    while (i < bytes.len) {
        const b0 = bytes[i];
        if (b0 < 0x80) {
            try out.append(alloc, b0);
            i += 1;
            continue;
        }
        const need: usize = switch (b0) {
            0xC2...0xDF => 2,
            0xE0...0xEF => 3,
            0xF0...0xF4 => 4,
            else => 0,
        };
        if (need == 0) {
            try out.appendSlice(alloc, "\u{FFFD}");
            i += 1;
            continue;
        }
        // Consume the longest well-formed prefix; the constraints on the byte after the
        // lead are what keep overlong forms and surrogates out.
        var k: usize = 1;
        while (k < need and i + k < bytes.len) : (k += 1) {
            const b = bytes[i + k];
            const ok = switch (k) {
                1 => switch (b0) {
                    0xE0 => b >= 0xA0 and b <= 0xBF,
                    0xED => b >= 0x80 and b <= 0x9F,
                    0xF0 => b >= 0x90 and b <= 0xBF,
                    0xF4 => b >= 0x80 and b <= 0x8F,
                    else => b >= 0x80 and b <= 0xBF,
                },
                else => b >= 0x80 and b <= 0xBF,
            };
            if (!ok) break;
        }
        if (k == need) {
            try out.appendSlice(alloc, bytes[i .. i + need]);
            i += need;
        } else {
            try out.appendSlice(alloc, "\u{FFFD}");
            i += k;
        }
    }
    return out.toOwnedSlice(alloc);
}

pub fn main(init: std.process.Init) !void {
    io_g = init.io;
    io_set = true;
    const alloc = init.gpa;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 3) {
        std.debug.print("usage: tokenizer <tok_ref.bin> <tokenizer.json>\n", .{});
        return error.BadArgs;
    }

    var tk = try Tokenizer.load(alloc, args[2]);
    defer tk.deinit();
    std.debug.print("tokenizer: {d} vocab ids, {d} merges, {d} added tokens, {d} interned symbols, unicode {s}\n", .{
        tk.n_vocab, tk.n_merges, tk.n_added, tk.syms.items.len, uni.version,
    });

    const ref_bytes = try readFile(alloc, args[1]);
    defer alloc.free(ref_bytes);
    // The rows and their id lists live until the process ends; an arena keeps that
    // leak-free without a per-blob free dance.
    var ref_arena = std.heap.ArenaAllocator.init(alloc);
    defer ref_arena.deinit();
    const rows = try readRef(ref_arena.allocator(), ref_bytes);
    std.debug.print("reference: {d} rows, {d} bytes\n", .{ rows.len, ref_bytes.len });

    try specialCheck(alloc, &tk);

    var matched: usize = 0;
    var mismatched: usize = 0;
    var dropped: usize = 0;
    var rt_rows: usize = 0;
    var rt_ok: usize = 0;
    for (rows, 0..) |row, ri| {
        var row_drops: usize = 0;
        const got = try tk.encodeCounted(alloc, row.text, &row_drops);
        defer alloc.free(got);
        dropped += row_drops;
        if (std.mem.eql(u32, got, row.ids)) {
            matched += 1;
            // decode() is not part of what the corpus checks ids against, so exercise it
            // here instead: on a row where nothing was dropped the text must come back.
            if (row_drops == 0) {
                const back = try tk.decode(alloc, got);
                defer alloc.free(back);
                rt_rows += 1;
                if (std.mem.eql(u8, back, row.text)) rt_ok += 1;
            }
            continue;
        }
        mismatched += 1;
        if (mismatched > 10) continue;
        const shown = try textPreview(alloc, row.text, 160);
        defer alloc.free(shown);
        std.debug.print("  MISMATCH row {d} [{s}] text=\"{s}\"\n", .{ ri, row.label, shown });
        std.debug.print("    {d} ids expected, {d} got\n", .{ row.ids.len, got.len });
        printIds("    want ids: ", row.ids);
        printIds("    got  ids: ", got);
        std.debug.print("    want split (byte-encoded, as the reference stores it):\n", .{});
        for (row.pieces[0..@min(row.pieces.len, 24)]) |pc| {
            const psh = try encodePreview(alloc, pc.text, 24);
            defer alloc.free(psh);
            std.debug.print("      '{s}' = ", .{psh});
            std.debug.print("(", .{});
            for (pc.ids, 0..) |id, k| {
                if (k > 0) std.debug.print(",", .{});
                std.debug.print("{d}", .{id});
            }
            std.debug.print(")\n", .{});
        }
        std.debug.print("    got  split (byte-encoded):\n", .{});
        const scratch = try alloc.alloc(u32, row.text.len);
        defer alloc.free(scratch);
        var dctx = DumpCtx{ .alloc = alloc, .tk = &tk, .scratch = scratch };
        try tk.walk(row.text, &dctx);
    }

    std.debug.print("  rows {d}, matched {d}, mismatched {d}, symbols dropped as not-in-vocab {d}\n", .{
        rows.len, matched, mismatched, dropped,
    });
    std.debug.print("  decode round-trip: {d} of {d} rows with no dropped symbol come back identical\n", .{
        rt_ok, rt_rows,
    });
    if (mismatched == 0 and matched == rows.len) {
        std.debug.print("  RESULT: PASS\n", .{});
    } else {
        std.debug.print("  RESULT: FAIL\n", .{});
        return error.Mismatch;
    }
}

/// `<|im_start|>` must come back as the single added-token id. Without the added-token
/// pass its regex pieces would BPE to a handful of unrelated ids, which is what this
/// prints underneath.
fn specialCheck(alloc: std.mem.Allocator, tk: *const Tokenizer) !void {
    const s = "<|im_start|>";
    const ids = try tk.encode(alloc, s);
    defer alloc.free(ids);
    std.debug.print("  special check: \"{s}\" -> ", .{s});
    printIds("", ids);
    const scratch = try alloc.alloc(u32, s.len);
    defer alloc.free(scratch);
    std.debug.print("    its pieces are:", .{});
    var p: usize = 0;
    while (p < s.len) {
        const n = pieceLen(s[p..]);
        var dropped: usize = 0;
        const shown = try encodePreview(alloc, s[p .. p + n], 8);
        defer alloc.free(shown);
        const syms = tk.encodePiece(s[p .. p + n], scratch, &dropped);
        std.debug.print(" '{s}'=(", .{shown});
        for (syms, 0..) |sym, k| {
            if (k > 0) std.debug.print(",", .{});
            std.debug.print("{d}", .{tk.sym_vocab.items[sym]});
        }
        std.debug.print(")", .{});
        p += n;
    }
    std.debug.print("\n", .{});
}
